extensions:
  basicauth/traces:
    client_auth:
      username: "${TEMPO_USERNAME}"
      password: "${TEMPO_PASSWORD}"
  basicauth/metrics:
    client_auth:
      username: "${PROMETHEUS_USERNAME}"
      password: "${PROMETHEUS_PASSWORD}"
  basicauth/logs:
    client_auth:
      username: "${LOKI_USERNAME}"
      password: "${LOKI_PASSWORD}"

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
  attributes/metrics:
    actions:
      - key: deployment.environment
        action: insert
        value: "${DEPLOY_ENV}"
      - key: "process_command_args"
        action: "delete"
  attributes/logs:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: container
      - action: insert
        key: loki.format
        value: raw

exporters:
  otlphttp:
    endpoint: "${TEMPO_ENDPOINT}"
    tls:
      insecure: true

  prometheusremotewrite:
    endpoint: "${PROMETHEUS_ENDPOINT}"
    auth:
      authenticator: basicauth/metrics

  otlphttp/loki:
    endpoint: "${LOKI_ENDPOINT}"
    auth:
      authenticator: basicauth/logs

service:
#  telemetry:
#    logs:
#      level: "DEBUG"
#      development: true
#      encoding: "json"
  extensions: [ basicauth/traces, basicauth/metrics, basicauth/logs ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlphttp ]

    metrics:
      receivers: [ otlp ]
      processors: [ batch,attributes/metrics ]
      exporters: [ prometheusremotewrite ]

    logs:
      receivers: [ otlp ]
      processors: [ batch,attributes/logs ]
      exporters: [ otlphttp/loki ]
